### ISSUE TITLE
CreateTags failure on new instances crashes run, leaving running (non terminated) instances

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky-aws#94]
The following is output to stderr (i.e. it's not in the log file)

```
Traceback (most recent call last):
  File "./bin/run-bluesky", line 73, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "./bin/run-bluesky", line 70, in main
    await runner.run(args.input)
  File "/bluesky-aws/blueskyaws/__init__.py", line 58, in run
    await self._run_all()
  File "/bluesky-aws/blueskyaws/__init__.py", line 158, in _run_all
    async with ec2_instance_manager:
  File "/bluesky-aws/blueskyaws/launch.py", line 35, in __aenter__
    await self._launch()
  File "/bluesky-aws/blueskyaws/launch.py", line 132, in _launch
    self._new_instances = await launcher.launch(new_instance_names)
  File "/usr/local/lib/python3.7/site-packages/afaws/ec2/launch.py", line 39, in launch
    instances = await self._create_instances()
  File "/usr/local/lib/python3.7/site-packages/afaws/ec2/launch.py", line 159, in _create_instances
    tags=self._options.get('tags', {}), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/afaws/ec2/resources.py", line 177, in create_multiple
    for i, instance in enumerate(instances)
  File "/usr/local/lib/python3.7/site-packages/afaws/ec2/resources.py", line 197, in _wait_to_name
    instance.create_tags(DryRun=False,Tags=instance_tags)
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the CreateTags operation: The instance ID 'i-099bf198066bbba1d' does not exist
```

**Comment by jdubowy** [comment]
Updated afaws, which now has retry logic, and added error handling code to catch post-launch errors (errors that happen in afaws launch logic) and terminate instnaces.
